import type { NextPage } from "next";
import Head from "next/head";
import { styles } from "../styles/styles";
import { Card } from "../components/Card";
import { PostsCell } from "../components/PostsCell";

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.appContainer}>
      <h1 className={styles.title}>
        Create <span className={styles.purple}>T3</span> App
      </h1>
      <p className={styles.body}>This stack uses:</p>
      <div className={styles.grid}>
        <Card name="Github" url="https://github.com/MarcinFilipek" />
        <Card
          name="LinkedIn"
          url="https://pl.linkedin.com/in/marcin-filipek-39b0a7189?trk=people-guest_people_search-card"
        />
        <Card name="Facebook" url="https://pl-pl.facebook.com/Marian.Cimek" />
        <Card name="Facebook" url="https://pl-pl.facebook.com/Marian.Cimek" />
      </div>
      <PostsCell />
    </main>
  </>
);

export default Home;
